# Конфигурация для расчета и хранения индикаторов
# =============================================

# База данных VPS
database:
  host: 82.25.115.144
  port: 5432
  database: trading_data
  user: trading_admin
  password: K9mX3pQ8vN5bR2tL7wY4zA6cE1dF0gH

# Таймфреймы для расчета индикаторов
timeframes:
  - 1m     # Минутные данные
  - 15m    # 15-минутные данные
  - 1h     # Часовые данные

# Символы для обработки
symbols:
  - BTCUSDT  # Начинаем с одной монеты

# Конфигурация индикаторов
indicators:
  # Simple Moving Average (начинаем с него)
  sma:
    enabled: true
    periods: [10, 20, 50, 100, 200]

  # Остальные индикаторы пока отключены
  ema:
    enabled: false
    periods: [9, 12, 21, 26, 50, 100, 200]

  rsi:
    enabled: false
    periods: [14]

# Параметры обработки
processing:
  batch_size: 10000      # Размер батча для обработки
  parallel_workers: 4    # Количество параллельных воркеров

# Логирование
logging:
  level: INFO
  file: indicators/logs/indicators.log